### ISSUE TITLE
ng2 call real API

### ISSUE THREAD

**Issue by Tony-Mc** [Tony-Mc/JumperCables#10]

**Comment by rubilnikas** [comment]
If need something I have this in another project: https://github.com/rubilnikas/ausryt-photo/blob/realese/src/AusrytPhoto.WEB/app/providers/portfolio/portfolioProvider.ts

**Comment by Tony-Mc** [comment]
Cool

**Comment by Tony-Mc** [comment]
Continue after #12 because we will need authentication/authorization in order to do secured calls.
